site_name: Learn Cryptography

nav:
    - 基本概念: basic.md
    - 凯撒密码: caesar
    - 置换密码: Substitution
    - One-Time Pad: one-time-pad
    - Pseudorandomness: pseudo-random
    - Stream Cipher: stream-cipher
    - Block Cipher: block-cipher
    - Diffie–Hellman Key Exchange: Diffie_Hellman-key-exchange
    - Public Key Infrastructure: RSA
    - Hash Function: hash
    - About: about.md


theme: readthedocs