site_name: Learn Cryptography

# plugins:
#   - section-index

nav:
    - Home: index.md
    - 基本概念: basic.md
    - 凯撒密码: caesar
    - 置换密码: Substitution
    - One-Time Pad: one-time-pad
    - Pseudorandomness: pseudo-random
    - Stream Cipher: stream-cipher
    - Block Cipher: block-cipher
    - Diffie–Hellman Key Exchange: Diffie_Hellman-key-exchange
    - RSA: RSA
    - Hash Function: hash
    - Digital Signature:
        - Overview: digital-signature/index.md
        - RSA Sign/Verify with Python: digital-signature/rsa-signature-python.md
        - RSA Sign/Verify with OpenSSL: digital-signature/rsa-signature-openssl.md
    - Message Authentication Codes(MAC): mac
    - Digital Certificates:
        - Overview: digital-certificates/index.md
        - Openssl Self-Sign Certificates: digital-certificates/openssl-self-sign.md
        - Chain of Certificates: digital-certificates/chain-of-trust.md
    - About: about.md


theme: readthedocs